name: primeira-pipe
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira action"
        run: echo "Hello World"

      - name: "Segunda action"
        run: |
          echo "Criado o primeiro workflow!"
          echo "Finalizando o workflow..."
  segundo-job:
    name: "Meu segundo job"
    runs-on: ubuntu-latest
    steps:
      - name: "Script Python"
        run: | 
          variavel = "Hellow World"
          print(variavel)
        shell: python
  terceiro-job:
    name: "Instalação ambiente node.js"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do node.js"
        run: node --version
      - name: "Definição da versão 20.13.1 do node.js"
      - uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: "Verificação da versão do node.js novamente"
        run: node --version
