name: primeira-pipe
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira action"
        run: echo "Hello World"

      - name: "Segunda action"
        run: |
          echo "Criado o primeiro workflow!"
          echo "Finalizando o workflow..."
